# Default values for hetida.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []

components:
  backend:
    installed_adapters: ""
    image:
      repository: hetida/designer-backend
      tag: ""
      pullPolicy: ""
    postgresql:
      address: postgres-postgresql
      adminPassword: postgres
      hetidaDbPassword: myHDSecret
    service:
      type: ClusterIP
      port: 8080
  frontend:
    image:
      repository: hetida/designer-frontend
      tag: ""
      pullPolicy: ""
    service:
      type: ClusterIP
      port: 8080
  runtime:
    image:
      repository: hetida/designer-runtime
      tag: ""
      pullPolicy: ""
    apiPrefix: "/runtime" # Overrides the api Prefix for runtime whose default is '/runtime'.
    service:
      type: ClusterIP
      port: 8090

# if adapters are provided as images
adapters:
  sample:
    enabled: false
    image:
      pullPolicy: IfNotPresent
      repository: some/repo
      tag: "1.0"
    service:
      type: ClusterIP
      port: 8080
    

# if needed so set storage class
# storageClass: default


nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


ingress:
  enabled: true
  issuerRef: {}
  hosts:
    - host: hetida.mydomain.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port: 8080
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: backend
              port: 8080
# if adapter is deployed
#        - path: /adapter-sample
#          pathType: Prefix
#          backend:
#            service:
#              name: adapter-sample
#              port: 8093
# if https-certs are provided
#  tls:
#    - hosts:
#        - hetida.mydomain.local
#      secretName: hetida.mydomain.local


tlsAuthDisabled: true

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
